# Подсказки:
# Формат: ЭФФЕКТ:УРОВЕНЬ:ДЛИТЕЛЬНОСТЬ_В_СЕКУНДАХ
# Пример: SPEED:1:15 = Скорость II на 15 секунд
# Уровень 0 = I, 1 = II и т.д.

# Эффекты зелий по версиям Minecraft:
# 🔹 Версии 1.8+
# - "SPEED:1:10"              # Скорость II
# - "SLOW:0:10"               # Замедление I
# - "HASTE:0:10"              # Спешка
# - "MINING_FATIGUE:0:10"     # Утомление
# - "STRENGTH:1:10"           # Сила II
# - "INSTANT_HEALTH:0:1"      # Мгновенное лечение I
# - "INSTANT_DAMAGE:0:1"      # Моментальный урон I
# - "JUMP_BOOST:1:10"         # Прыгучесть II
# - "NAUSEA:0:5"              # Тошнота
# - "REGENERATION:1:10"       # Регенерация II
# - "RESISTANCE:0:10"         # Сопротивление урону
# - "FIRE_RESISTANCE:0:10"    # Огнестойкость
# - "WATER_BREATHING:0:10"    # Подводное дыхание
# - "INVISIBILITY:0:10"       # Невидимость
# - "BLINDNESS:0:5"           # Слепота
# - "NIGHT_VISION:0:10"       # Ночное зрение
# - "HUNGER:0:10"             # Голод
# - "WEAKNESS:0:10"           # Слабость
# - "POISON:0:10"             # Отравление
# - "WITHER:0:10"             # Иссушение
# - "HEALTH_BOOST:0:10"       # Доп. здоровье
# - "ABSORPTION:0:10"         # Поглощение
# - "SATURATION:0:1"          # Сытость (мгновенная)

# 🔹 Версии 1.9 — 1.13
# - "GLOWING:0:10"            # Свечение
# - "LEVITATION:0:5"          # Левитация
# - "LUCK:0:10"               # Удача
# - "UNLUCK:0:10"             # Неудача

# 🔹 Версии 1.13 — 1.14+
# - "SLOW_FALLING:0:10"       # Плавное падение
# - "CONDUIT_POWER:0:10"      # Сила источника
# - "DOLPHINS_GRACE:0:10"     # Ловкость дельфина

# 🔹 Версии 1.14 — 1.16+
# - "BAD_OMEN:0:60"           # Дурное знамение
# - "HERO_OF_THE_VILLAGE:0:60" # Герой деревни

# 🔹 Версия 1.19+
# - "DARKNESS:0:10"           # Темнота

# 🔹 Версия 1.21+
# - "WIND_CHARGED:0:10"       # Заряд ветра
# - "WEAVING:0:10"            # Плетение
# - "OOZING:0:10"             # Слизь
# - "INFESTED:0:10"           # Заражение
# - "RAID_OMEN:0:60"          # Знамение рейда
# - "TRIAL_OMEN:0:60"         # Знамение испытания


potions:
  bablgam:
    name: "&fЭликсир &dБабл-Гам&f "
    lore:
      - ""
      - "&fСопротивление I &7(1:00)"
      - "&fПрилив здоровья II &7(1:00)"
      - "&fРегенерация II &7(0:18)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: false
    effects:
      - "DAMAGE_RESISTANCE:0:60"
      - "REGENERATION:1:18"
      - "HEALTH_BOOST:1:60"

  bablsplash:
    name: "&fБутыль &dБабл-Гама&f "
    lore:
      - ""
      - "&fСопротивление I &7(1:00)"
      - "&fПрилив здоровья II &7(1:00)"
      - "&fРегенерация II &7(0:18)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: true
    effects:
      - "DAMAGE_RESISTANCE:0:60"
      - "REGENERATION:1:18"
      - "HEALTH_BOOST:1:60"

  rega:
    name: "&fЗелье &dРегенерации"
    lore:
      - ""
      - "&fРегенерация III &7(0:21)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: false
    effects:
      - "REGENERATION:2:21"

  energy:
    name: "&aЭнергетик "
    lore:
      - ""
      - "&fСопротивление II &7(1:00)"
      - "&fПрилив здоровья II &7(1:00)"
      - "&fСкорость II &7(0:39)"
      - "&fСуперпрыжок II &7(0:39)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: true
    effects:
      - "DAMAGE_RESISTANCE:1:60"
      - "SPEED:1:39"
      - "HEALTH_BOOST:1:60"
      - "JUMP:1:39"

  kislota:
    name: "&2Кислота "
    lore:
      - ""
      - "&fОтравление I &7(1:00)"
      - "&fМедлительность II &7(1:00)"
      - "&fИссушение I &7(0:15)"
      - "&fСлабость II &7(0:21)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: true
    effects:
      - "POISON:0:60"
      - "SLOW:2:60"
      - "WITHER:0:15"
      - "WEAKNESS:1:21"

  silka:
    name: "&fЗелье &6Силы III"
    lore:
      - ""
      - "&fСила III &7(1:30)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: false
    effects:
      - "INCREASE_DAMAGE:2:90"

  inviz:
    name: "&fЗелье &8Невидимости"
    lore:
      - ""
      - "&fНевидимость &7(15:00)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: false
    effects:
      - "INVISIBILITY:0:900"

  skorka:
    name: "&fЗелье &bСкорости III"
    lore:
      - ""
      - "&fСкорость III &7(1:30)"
    color: "253,245,0"
    hideAttributes: true
    splash_potion: false
    effects:
      - "SPEED:2:90"

  otrizka:
    name: "&fЗелье &2Отрыжки"
    lore:
      - ""
      - "&cЗамедление III &7(0:35)"
      - "&cСлепота I &7(0:15)"
      - "&cИссушение V &7(0:10)"
      - "&cГолод X &7(1:00)"
      - "&cСлабость III &7(1:00)"
    color: "105,105,105"
    hideAttributes: true
    splash_potion: true
    effects:
      - "SLOW:2:35"
      - "BLINDNESS:0:15"
      - "WITHER:4:10"
      - "HUNGER:9:60"
      - "WEAKNESS:2:60"

  pobedilka:
    name: "&fЗелье &aПобедителя"
    lore:
      - ""
      - "&fСопротивление II &7(1:00)"
      - "&fПрилив здоровья II &7(1:00)"
      - "&fСкорость II &7(0:39)"
      - "&fНевидимость I &7(15:00)"
    color: "105,105,105"
    hideAttributes: true
    splash_potion: true
    effects:
      - "DAMAGE_RESISTANCE:1:60"
      - "SPEED:1:39"
      - "HEALTH_BOOST:1:60"
      - "INVISIBILITY:0:900"

  killerka:
    name: "&fЗелье &4Киллера"
    lore:
      - ""
      - "&fСила IV &7(1:00)"
      - "&fСопротивление II &7(1:00)"
    color: "105,105,105"
    hideAttributes: true
    splash_potion: true
    effects:
      - "INCREASE_DAMAGE:3:60"
      - "DAMAGE_RESISTANCE:1:60"
messages:
  no_permission: "&f[&9LC&f] У вас нет &9прав&f для использования этой &9команды"
  usage: "&f[&9LC&f] &fИспользование: &9/zpotion give <игрок> <зелье>"
  unknown_command: "&f[&9LC&f] &fНеизвестная &9команда"
  player_not_found: "&f[&9LC&f] &fИгрок не &9найден"
  potion_not_found: "&f[&9LC&f] &fЗелье не &9найдено"
  potion_received: "&f[&9LC&f] &fВы &9получили&f %potion%"